version: '3.1'
services:
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
    environment:      
      MYSQL_ROOT_PASSWORD: pwd
    expose:
      - "3306"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "225MB"

  backend:
    build: .    
    expose:
      - "6969"
    depends_on:
      - db    
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "225MB"
    

  
